# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c986234e435814aa03101a127744df55af3e72f61eeb73a6136bbea0f8fff61eb73f115ac6e3b16467b2ab10156ac43fbb9675b88421b6d90de7f3404a321a7

test:
  secret_key_base: 925cbf997644c5987bcc299b533bc8c7dadc6b47d8f329e738f92a7d6c8e94d0b3659a8b0268960d7cea731424bd45d415a0e807cb04e3c8057aae4b3654b2c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
